name: CI

on:
  push:
    branches-ignore:
    - 'release/**'
    paths-ignore:
    - '**/*.md'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
    - '**/*.md'

jobs:
  build-Android:
    runs-on: windows-2019

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.2.21155.3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install dependencies
      run: |
        msbuild /t:restore ./Nivaes.TimeLine.Droid/
        msbuild /t:restore ./Nivaes.TimeLine.Droid.Sample/

    - name: Build DropBox.Core.Sdk.Droid
      run: dotnet build .\Droid\Bindings\DropBox.Core.Sdk.Droid\ /property:Configuration=Release  

    #- name: Build App.Cross.Droid
    #  run: msbuild ./Nivaes.TimeLine.Droid/ /property:Configuration=Release

    #- name: Build App.Cross.Droid
    #  run: dotnet build ./Nivaes.TimeLine.Droid/ --configuration Release

  build-iOS:
    runs-on: macos-10.15

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.2.21155.3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install dependencies
      run: |
        msbuild /t:restore ./Nivaes.TimeLine.iOS/
        msbuild /t:restore ./Nivaes.TimeLine.iOS.Sample/

    #- name: Build App.Cross.iOS
    #  run: msbuild ./Nivaes.TimeLine.iOS/ /property:Configuration=Release

    #- name: Build App.Cross.iOS
    #  run: dotnet build ./Nivaes.TimeLine.Droid/ --configuration Release

  #build-Windows:
  #  runs-on: windows-2019
  #  steps:
  #  - name: Dump GitHub context
  #    env:
  #      GITHUB_CONTEXT: ${{ toJson(github) }}
  #    run: echo "$GITHUB_CONTEXT"

  #  - name: Checkout
  #    uses: actions/checkout@v2

    #- name: Setup .NET Core 3.1.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 3.1.x

    #- name: Setup .NET Core 5.0.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 5.0.x
    #    source-url: https://nuget.pkg.github.com/Nivaes/index.json
    #  env:
    #    NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    #- name: Setup .NET Core 6.0.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 6.0.100-preview.1.21103.13

    #- name: Setup MSBuild
    #  uses: microsoft/setup-msbuild@v1.0.2

    #- name: Install dependencies
    #  run: |
    #    msbuild /t:restore ./Nivaes.TimeLine.WinUI.UWP/
    #    msbuild /t:restore ./Nivaes.TimeLine.WinUI.UWP.Sample/
    #    msbuild /t:restore ./Nivaes.TimeLine.WinUI.WPF.Sample/

    #- name: Build App.Cross.WinUI
    #  run: msbuild ./Nivaes.TimeLine.WinUI/ /property:Configuration=Release

    #- name: Build App.Cross.WPF
    #  run: msbuild ./Nivaes.TimeLine.WinUI.WPF.Sample/ /property:Configuration=Release
