name: CI

on:
  push:
    branches-ignore:
    - 'release/**'
    paths-ignore:
    - '**/*.md'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
    - '**/*.md'

#env:
#    ANDROIDWORKLOADSMSI: "https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4534967/main/f4d8fe238b15eadfc7842749bf13e5fca3e2f2d2/Microsoft.NET.Workload.Android.11.0.200.148.msi"
#    IOSWORKLOADSMSI: "https://bosstoragemirror.azureedge.net/wrench/main/98c8649d0c7d1e3c4c8d8d09e022befa853fb1e7/4541181/package/Microsoft.NET.Workload.iOS.14.4.100-ci.main.1192.msi"
#    ANDROIDWORKLOADSAPK: "https://download.visualstudio.microsoft.com/download/pr/5e10dc75-294e-49f4-972e-218ae86191a3/e46d3533c30c8a864252a334820263a9/dotnet-sdk-6.0.100-preview.2.21155.3-osx-x64.pkg"
#    IOSWORKLOADSAPK: "https://bosstoragemirror.azureedge.net/wrench/main/98c8649d0c7d1e3c4c8d8d09e022befa853fb1e7/4541181/package/notarized/Microsoft.iOS.Bundle.14.4.100-ci.main.1192.pkg"
#    MACCATALYSTWORKLOADSAPK: "https://bosstoragemirror.azureedge.net/wrench/main/98c8649d0c7d1e3c4c8d8d09e022befa853fb1e7/4541181/package/notarized/Microsoft.MacCatalyst.Bundle.14.3.100-ci.main.337.pkg"

jobs:
  build-Android:
    runs-on: windows-2019

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.2.21155.3
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install Android Workloads
      shell: pwsh
      run: |
        dotnet tool install --global boots
        boots https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4534967/main/f4d8fe238b15eadfc7842749bf13e5fca3e2f2d2/Microsoft.NET.Workload.Android.11.0.200.148.msi
        boots https://bosstoragemirror.azureedge.net/wrench/main/98c8649d0c7d1e3c4c8d8d09e022befa853fb1e7/4541181/package/Microsoft.NET.Workload.iOS.14.4.100-ci.main.1192.msi

    #- name: Install Android Workloads
    #  shell: pwsh
    #  run: |
    #    dotnet tool install --global boots
    #    boots ${{ ANDROIDWORKLOADSMSI }}

    #- name: Install dotnet
    #  run: |
    #    Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
    #    .\dotnet-install.ps1 -Version $(DotNetVersion) -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
    #    dotnet --list-sdks

    #- name: Restore dependencies
    #  run: |
    #    msbuild /t:restore .\Droid\Bindings\DropBox.Core.Sdk.Droid\
    #    msbuild /t:restore .\Droid\JitsiBindings\Facebook.ReactNative.Keep.Awake.Droid\
    #    msbuild /t:restore .\Droid\JitsiMeet.Droid.Sample\

    #- name: MsBuild DropBox.Core.Sdk.Droid
    #  run: msbuild .\Droid\Bindings\DropBox.Core.Sdk.Droid\ /property:Configuration=Release

    #- name: MsBuild Facebook.ReactNative.Keep.Awake.Droid
    #  run: msbuild .\Droid\JitsiBindings\Facebook.ReactNative.Keep.Awake.Droid\ /property:Configuration=Release

    #- name: MsBuild JitsiMeet.Droid.Sample
    #  run: msbuild .\Droid\JitsiMeet.Droid.Sample\ /property:Configuration=Release

    - name: Build DropBox.Core.Sdk.Droid
      run: dotnet build .\Droid\Bindings\DropBox.Core.Sdk.Droid\ /property:Configuration=Release

    #- name: Facebook.ReactNative.Keep.Awake.Droid
    #  run: dotnet build .\Droid\JitsiBindings\Facebook.ReactNative.Keep.Awake.Droid\ /property:Configuration=Release

    #- name: Build DropBox.Core.Sdk.Droid
    #  run: dotnet build .\Droid\JitsiMeet.Droid.Sample\JitsiMeet.Droid.Sample.csproj /property:Configuration=Release

  build-iOS:
    runs-on: macos-10.15

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x


    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.2.21155.3
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install iOS Workloads
      run: |
        dotnet tool install --global boots
        boots https://download.visualstudio.microsoft.com/download/pr/5e10dc75-294e-49f4-972e-218ae86191a3/e46d3533c30c8a864252a334820263a9/dotnet-sdk-6.0.100-preview.2.21155.3-osx-x64.pkg
        boots https://bosstoragemirror.azureedge.net/wrench/main/98c8649d0c7d1e3c4c8d8d09e022befa853fb1e7/4541181/package/notarized/Microsoft.iOS.Bundle.14.4.100-ci.main.1192.pkg
        boots https://bosstoragemirror.azureedge.net/wrench/main/98c8649d0c7d1e3c4c8d8d09e022befa853fb1e7/4541181/package/notarized/Microsoft.MacCatalyst.Bundle.14.3.100-ci.main.337.pkg

    #- name: Install iOS Workloads
    #  run: |
    #    dotnet tool install --global boots
    #    boots ${{ IOSWORKLOADSAPK }}
    #    boots ${{ MACCATALYSTWORKLOADSAPK }}


    #- name: Install dependencies
    #  run: |
    #    msbuild /t:restore ./Nivaes.TimeLine.iOS/
    #    msbuild /t:restore ./Nivaes.TimeLine.iOS.Sample/

    - name: Build JitsiMeet.Sdk.iOS
      run: dotnet build .\iOS\Jitsibindings\JitsiMeet.Sdk.iOS\ /property:Configuration=Release

    - name: Build JitsiMeet.iOS.Sample
      run: dotnet build dotnet build .\iOS\JitsiMeet.iOS.Sample\ --configuration Release

  #build-Windows:
  #  runs-on: windows-2019
  #  steps:
  #  - name: Dump GitHub context
  #    env:
  #      GITHUB_CONTEXT: ${{ toJson(github) }}
  #    run: echo "$GITHUB_CONTEXT"

  #  - name: Checkout
  #    uses: actions/checkout@v2

    #- name: Setup .NET Core 3.1.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 3.1.x

    #- name: Setup .NET Core 5.0.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 5.0.x
    #    source-url: https://nuget.pkg.github.com/Nivaes/index.json
    #  env:
    #    NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    #- name: Setup .NET Core 6.0.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 6.0.100-preview.1.21103.13

    #- name: Setup MSBuild
    #  uses: microsoft/setup-msbuild@v1.0.2

    #- name: Install dependencies
    #  run: |
    #    msbuild /t:restore ./Nivaes.TimeLine.WinUI.UWP/
    #    msbuild /t:restore ./Nivaes.TimeLine.WinUI.UWP.Sample/
    #    msbuild /t:restore ./Nivaes.TimeLine.WinUI.WPF.Sample/

    #- name: Build App.Cross.WinUI
    #  run: msbuild ./Nivaes.TimeLine.WinUI/ /property:Configuration=Release

    #- name: Build App.Cross.WPF
    #  run: msbuild ./Nivaes.TimeLine.WinUI.WPF.Sample/ /property:Configuration=Release
